{% set name = "chemics" %}
{% set version = "23.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemics-{{ version }}.tar.gz
  sha256: 2823034657304652edc02b6df05b70df680744cc369251d62763d049819d0e39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - hatchling
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - chemics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chemics/chemics
  summary: A Python package for chemical engineering
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  description: |
    The Chemics package is a collection of Python functions for conducting 
    calculations in the field of chemical and fluidization engineering.
  doc_url: https://github.com/chemics/chemics
  dev_url: https://github.com/chemics/chemics

extra:
  recipe-maintainers:
    - jan-janssen
