{% set name = "chemics" %}
{% set version = "20.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b69ad78af651a8c37f0b5770ec97bb59cf8779739f68310393c2c3db12fdc6e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - chemics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chemics/chemics
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for chemical reactor engineering

  description: |
    The Chemics package is a collection of Python functions for conducting 
    calculations in the field of chemical and fluidization engineering.
  doc_url: https://github.com/chemics/chemics
  dev_url: https://github.com/chemics/chemics

extra:
  recipe-maintainers:
    - jan-janssen
    - wigging
